### ISSUE TITLE
No Module 'aenet' is created when setup.py is installed

### ISSUE THREAD

**Issue by Ipvikukiepki-KQS** [znaoya/aenet#2]
As per the Given Instructions, I have created an export directory and downloaded all model files by running download.sh and when setup.py install is run, I get three locked files but no module named 'aenet' is created, hence I could not import aenet and hance run_sample.py module could not be run. Please give me any kind of information.

**Comment by JianCao92** [comment]
Hi Sarvin92,
I was trying to run the code and couldn't find the 'aenet' module either. Wonder if you have solved the problem? Thanks a lot for help!

Jian

**Comment by Ipvikukiepki-KQS** [comment]
Hallo Jiancao92,

I could run the code successfully. If you still have problem in running the
code, I shall give you the information on solving it.

With regards,
Saran

**Comment by JianCao92** [comment]
Hi Saran,

I could directly run it now. Didn't try installing it as a package again, since I'll need to modify the codes anyway. Thank you so much for offering to help :)

Regards,
Jian

**Comment by Ipvikukiepki-KQS** [comment]
Hi Jian,

You are welcome :)

By the way, Are you interested in Knowledge Transfer? I hope that it would
be interesting as we work on the same domain. Could you let me know when
you are interested in it?

With regards,
Saran

**Comment by JianCao92** [comment]
Yes I'm interested in transfer learning & its application in acoustic event detection, etc.
