### ISSUE TITLE
Is there a document of HCopy?

### ISSUE THREAD

**Issue by KeyKy** [znaoya/aenet#3]
I found that it is hard to understand the intension of following code.

```
cmd = self.HCopyExe + ' -C ' + self.HConfigFile + ' -S ' + scriptfile
```

**Comment by sushanb** [comment]
Bumping this thread. I am having a hard time installing the right HCopy. Any help/insights will be appreciated. 
Thanks Sushan

**Comment by afperezm** [comment]
I could only find the following reference regarding [HCopy](https://labrosa.ee.columbia.edu/doc/HTKBook21/HTKBook.html) but it covers other tooling and not only HCopy. From my understanding HCopy is a tool to extract log mel-filter bank channel outputs for a given waveform audio file. In particular it uses the config file obtained by the `download.sh` script which contains several configurations like `SOURCEKIND = WAVEFORM` and `TARGETKIND = FBANK_E_D_A` and processes the files as specified by script file which is a temporary file containing the files to process as follows:

```
wav/airplane_2.wav /tmp/tmpYAHuQB/airplane_2.mfb
wav/acoustic_guitar_60.wav /tmp/tmpYAHuQB/acoustic_guitar_60.mfb
```

It shouldn't be necessary to download and install HCopy as it is already provided. Personally I could use as-is from Ubuntu 16.04.3 LTS.

**Comment by gyglim** [comment]
How to obtain **HCopy**, see: http://htk.eng.cam.ac.uk/download.shtml, as stated in the requirements:
https://github.com/znaoya/aenet/blob/master/README.md#requirements

Indeed, we use it to extract the filter bank features, as @gantzer89 has observed.

`cmd = self.HCopyExe + ' -C ' + self.HConfigFile + ' -S ' + scriptfile` defines the command we use to extract the filters, with the configuration defined in `self.HConfigFile`, which is the following file:
https://data.vision.ee.ethz.ch/cvl/aenet_feat_data/configmfb.hcopy
and `scriptfile` being a file containing the wav files for which features are extracted
